name: New Snippet
description: Submit you new snippet here.
body:
  - type: input
    id: snippet-id
    attributes:
      label: Snippet ID
      description: "What is the ID of the snippet (this will be the folder of the snippet)"
      placeholder: "lambda-function-convert-s3-storageclass"
    validations:
      required: true  
  - type: input
    id: title
    attributes:
      label: Title of the Snippet
      description: "Title shown on ServerlessLand."
      placeholder: "Connect to Amazon RDS from Lambda"
    validations:
      required: true  
  - type: input
    id: subtitle
    attributes:
      label: Subtitle
      description: "Small subtitle for the snippet snippet"
      placeholder: "This snippet demonstrates how to connect to an  Amazon RDS database from an AWS Lambda function with IAM authentication. This snippet is valid for MariaDB/MySQL or Aurora for MySQL"
    validations:
      required: true  
  - type: input
    id: description
    attributes:
      label: Description
      description: "Description of the snippet. Describe what it does, or how to use it."
      placeholder: "Amazon Relational Database Service (Amazon RDS) is a collection of managed services that makes it simple to set up, operate, and scale databases in the cloud. Choose from seven popular engines. Connect to an RDS database using IAM authentication."
    validations:
      required: true  
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Type of snippet.
      options:
        - AWS CLI
        - CloudWatch Logs Insights
        - Integration
        - Step Functions intrinsic functions
        - Tools
  - type: checkboxes
    id: services
    attributes:
      label: Which services are related to this snippet?
      description: You may select more than one.
      options:
        - label: AWS Amplify
        - label: AWS AppSync
        - label: AWS AppConfig
        - label: AWS Config
        - label: AWS Organizations
        - label: Amazon Managed Grafana
        - label: Amazon Managed Service for Prometheus
        - label: AWS Security Hub
        - label: Amazon API Gateway
        - label: AWS App Runner
        - label: Amazon Athena
        - label: AWS Batch
        - label: Amazon Bedrock
        - label: Amazon Inspector
        - label: Amazon Cognito
        - label: AWS CodeCommit
        - label: AWS CodePipeline
        - label: Amazon CodeWhisperer
        - label: Amazon Connect
        
  - type: checkboxes
    id: languages
    attributes:
      label: What programming languages can be applied to this snippet?
      description: You may select more than one.
      options:
        - label: .NET
        - label: Go
        - label: Java
        - label: JavaScript
        - label: Node
        - label: PHP
        - label: Python
        - label: Ruby
        - label: TypeScript
        - label: VTL
        - label: aws cli
        - label: bash
        - label: json
  - type: markdown
    attributes:
      value: "---"      
  - type: textarea
    id: snippet-title
    attributes:
      label: Snippet title
      description: "This short title gets render above the snippet."
      placeholder: "Parameter mapping to remove custom headers from Request and Response"
    validations:
      required: true
  - type: textarea
    id: snippet
    attributes:
      label: Snippet
      description: "The snippet code"
      render: bash
      placeholder: |
        aws apigatewayv2 update-integration \
        --api-id $API 
        --integration-id $INTEGRATION_ID 
        --request-parameters {\"remove:header.custom_headerA\":\"\'\'\"} \
        --response-parameters {\"200\":{\"remove:header.headerB\":\"\'\'\"}}
    validations:
      required: true