name: New Snippet
description: Submit you new snippet here.
body:
  - type: input
    id: snippet-id
    attributes:
      label: Snippet ID
      description: "What is the ID of the snippet (this will be the folder of the snippet)"
      placeholder: "lambda-function-convert-s3-storageclass"
    validations:
      required: true  
  - type: input
    id: title
    attributes:
      label: Title of the Snippet
      description: "Title shown on ServerlessLand."
      placeholder: "Connect to Amazon RDS from Lambda"
    validations:
      required: true  
  - type: input
    id: subtitle
    attributes:
      label: Subtitle
      description: "Small subtitle for the snippet snippet"
      placeholder: "This snippet demonstrates how to connect to an  Amazon RDS database from an AWS Lambda function with IAM authentication. This snippet is valid for MariaDB/MySQL or Aurora for MySQL"
    validations:
      required: true  
  - type: input
    id: description
    attributes:
      label: Description
      description: "Description of the snippet. Describe what it does, or how to use it."
      placeholder: "Amazon Relational Database Service (Amazon RDS) is a collection of managed services that makes it simple to set up, operate, and scale databases in the cloud. Choose from seven popular engines. Connect to an RDS database using IAM authentication."
    validations:
      required: true  
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Type of snippet.
      options:
        - AWS CLI
        - CloudWatch Logs Insights
        - Integration
        - Step Functions intrinsic functions
        - Tools
  - type: checkboxes
    id: services
    attributes:
      label: Which services are related to this snippet?
      description: You may select more than one.
      options:
        - label: AWS Amplify
        - label: AWS AppSync
        - label: AWS AppConfig
        - label: AWS Organizations
        - label: Amazon Managed Grafana
        - label: Amazon Managed Service for Prometheus
        - label: AWS Security Hub
        - label: Amazon API Gateway
        - label: AWS App Runner
        - label: Amazon Athena
        - label: AWS Batch
        - label: Amazon Bedrock
        - label: Amazon Inspector
        - label: Amazon Cognito
        - label: AWS CodeCommit
        - label: AWS CodePipeline
        - label: Amazon CodeWhisperer
        - label: Amazon Connect
        - label: AWS Config
        - label: Amazon Comprehend
        - label: Amazon CloudFormation
        - label: Amazon CloudFront Edge
        - label: Amazon CloudFront Functions
        - label: Amazon CloudFront
        - label: Amazon CloudWatch
        - label: Amazon DynamoDB
        - label: Amazon DynamoDB Streams
        - label: Amazon ECS
        - label: Amazon ElastiCache
        - label: Amazon EFS
        - label: Amazon Polly
        - label: AWS Elemental
        - label: AWS Elemental MediaConnect
        - label: AWS Elemental MediaLive
        - label: AWS Elemental MediaConvert
        - label: Amazon EventBridge
        - label: Amazon EventBridge Pipes
        - label: Amazon EventBridge API Destinations
        - label: Amazon EventBridge Scheduler
        - label: Amazon DevOps Guru
        - label: Amazon FSx
        - label: AWS Fargate
        - label: AWS Glue
        - label: Amazon HealthLake
        - label: AWS IoT
        - label: Amazon SES
        - label: AWS Identity & Access Management
        - label: Amazon Kendra
        - label: Amazon Kinesis Data Streams
        - label: Amazon Kinesis Video Streams
        - label: Amazon Kinesis Firehose
        - label: Amazon QLDB
        - label: Amazon RDS
        - label: Amazon Sagemaker
        - label: Amazon S3
        - label: Amazon SNS
        - label: Amazon SQS
        - label: AWS Systems Manager
        - label: Amazon Transcribe
        - label: AWS Lambda
        - label: Amazon MemoryDB for Redis
        - label: Amazon Pinpoint
        - label: Amazon MSK
        - label: Amazon Redshift
        - label: Amazon Rekognition
        - label: AWS Secrets Manager
        - label: Amazon Textract
        - label: AWS Transfer
        - label: AWS Step Functions
        - label: AWS WAF
        - label: Amazon VPC
        - label: Amazon Route 53
        - label: AWS CloudTrail
        - label: AWS Cloud9
        - label: Amazon Translate
        - label: Amazon Elastic Compute Cloud
        - label: AWS SAM CLI
        - label: Application Load Balancer
        - label: AWS Service Catalog
        - label: AWS Resource Explorer
        - label: AWS Elastic Disaster Recovery
        - label: AWS Trusted Advisor
        - label: Elastic Container Service
        - label: AWS Control Tower
        - label: Amazon RDS Proxy
        - label: Amazon Aurora
        - label: AWS Chatbot
        - label: AWS Audit Manager
        - label: AWS X-Ray
        - label: VPC Link
        - label: Amazon VPC Lattice
        - label: AWS CodeBuild
        - label: Amazon QuickSight
        - label: AmazonMQ RabbitMQ
        - label: Amazon Timestream
        - label: Amazon OpenSearch
        - label: AWS Compute Optimizer
        - label: Amazon Elastic Kubernetes Service (EKS)
        - label: Amazon Kinesis
        - label: Amazon Managed Workflows for Apache Airflow
        - label: Amazon Elastic Map Reduce
        - label: Managed Service for Apache Flink
        - label: Amazon DocumentDB
        - label: AWS Application Composer
  - type: checkboxes
    id: languages
    attributes:
      label: What programming languages can be applied to this snippet?
      description: You may select more than one.
      options:
        - label: .NET
        - label: Go
        - label: Java
        - label: JavaScript
        - label: Node
        - label: PHP
        - label: Python
        - label: Ruby
        - label: TypeScript
        - label: VTL
        - label: aws cli
        - label: bash
        - label: json
  - type: markdown
    attributes:
      value: "---"      
  - type: textarea
    id: snippet-title
    attributes:
      label: Snippet title
      description: "This short title gets render above the snippet."
      placeholder: "Parameter mapping to remove custom headers from Request and Response"
    validations:
      required: true
  - type: textarea
    id: snippet
    attributes:
      label: Snippet
      description: "The snippet code"
      render: bash
      placeholder: |
        aws apigatewayv2 update-integration \
        --api-id $API 
        --integration-id $INTEGRATION_ID 
        --request-parameters {\"remove:header.custom_headerA\":\"\'\'\"} \
        --response-parameters {\"200\":{\"remove:header.headerB\":\"\'\'\"}}
    validations:
      required: true